apiVersion: v1
kind: Service
metadata:
  name: ucg-web-server
  labels:
     app: ucg-web-server
spec:
  selector:
    app: ucg-web-server
  type: LoadBalancer
  externalIPs : ["169.60.13.110"]
  ports:
   - protocol: TCP  
     port: 80