kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: ucg-web-server-code-prod
 annotations:
   volume.beta.kubernetes.io/storage-class: ""
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: "100Gi"