zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"

app:
  image: node:slim
  links: 
    - zookeeper:zk
  volumes:
    - ../../:/code
  working_dir: /code
  environment:
    - BOT_CONFIG_FILE=${BOT_CONFIG_FILE}
    - ucg_domain=ucg-cluster-dev.us-south.containers.mybluemix.net
    - wcs_username=4acac659-e820-4ef6-8421-e88f517c9c4c
    - wcs_password=k0gYo1FjJymP
    - workspace_id=54141f49-ffa2-4f6b-887c-aac6aea5d42d
  command: node examples/cluster/index.js
  

