kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: clientsandbox-nodered-data-dev
 annotations:
   volume.beta.kubernetes.io/storage-class: ""
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: "100Gi"