#++++++++++++++++++++++++++++++++++++++
# Apline PHP-Apache Docker container
#++++++++++++++++++++++++++++++++++++++

FROM webdevops/php-apache:alpine-php7

#Copy Carla zip into html direcory
COPY carla-release-v3-2/  /opt/htdocs/

