apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ucg-ingress
spec:
  tls:
  - hosts:
    - ucg-clusterv3.us-south.containers.mybluemix.net
    secretName: ucg-clusterv3
  rules:
  - host: ucg-clusterv3.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /
        backend:
          serviceName: ucg-web-server
          servicePort: 80
      - path: /admin
        backend:
          serviceName: ucg-nodered
          servicePort: 1880   
      - path: /load
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /liveperson
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /mobile
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /Alexa
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /sip
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /GoogleHome
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /slack
        backend:
          serviceName: ucg-nodered
          servicePort: 1880
      - path: /smooch
        backend:
          serviceName: ucg-nodered
          servicePort: 1880