apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodered
spec:
  replicas: 40
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: dennisnotojr/nodered-loadtest:version16
        ports: 
         - containerPort: 1880
           protocol: TCP
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.60
            memory: 512Mi
          requests:  
            cpu: 0.25
            memory: 256Mi
        env:
        - name: NODE_ENV
          value: "production"