apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
     app: nodered
spec:
  selector:
    app: nodered
  type: LoadBalancer
  externalIPs : ["169.60.13.110"]
  ports:
   - protocol: TCP  
     port: 1880

