kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    type: HostPath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/root/UCG-Repo-master/UCG/Docker/data"