apiVersion: v1
kind: Service
metadata:
  name: ucg-carla
  labels:
     app: ucg-carla
spec:
  selector:
    app: ucg-carla
  type: LoadBalancer
  ports:
   - protocol: TCP  
     port: 80
     name : tcp-80
   - protocol: TCP  
     port: 443
     name : tcp-443
