apiVersion: v1
kind: PersistentVolume
metadata:
 name: ucg-carla-htdocs-prod
spec:
 capacity:
   storage: "100Gi"
 accessModes:
   - ReadWriteMany
 nfs:
   server: "fsf-dal1001h-fz.adn.networklayer.com"
   path: "/IBM02SV1339641_2/data01/ucg-carla-htdocs-prod"