apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../../Kubernetes/kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - args:
        - node
        - examples/cluster/index.js
        env:
        - name: BOT_CONFIG_FILE
          value: examples/cluster/local/agents.json
        image: node:slim
        name: app
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: app-claim0
        workingDir: /code
      restartPolicy: Always
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
status: {}
