apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ucg-liveperson-bot 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ucg-liveperson-bot
    spec:
      containers:
      - name: zookeeper-lp
        image: wurstmeister/zookeeper
        ports:
         - containerPort: 2181
           protocol: TCP 
      - name: app-lp
        image: node:slim
        ports:
        - name: headless
          containerPort: 55555
        args:
          - node
          - examples/cluster/index.js
        env:
          - name: BOT_CONFIG_FILE
            value: examples/cluster/local/agents.json
          - name: ZK_PORT_2181_TCP_PORT
            value: "2181"
          - name: ZK_PORT_2181_TCP_ADDR
            value: "127.0.0.1"
          - name: ucg_domain
            value: "ucg-clusterdev.us-south.containers.mybluemix.net"
          - name: wcs_username
            value: "4acac659-e820-4ef6-8421-e88f517c9c4c"
          - name: wcs_password
            value: "k0gYo1FjJymP"
          - name: workspace_id
            value: "54141f49-ffa2-4f6b-887c-aac6aea5d42d"  
        volumeMounts:
          - mountPath: /code
            name: code
        workingDir: /code
      volumes:
        - name: code
          persistentVolumeClaim:
           claimName: ucg-liveperson-code-prod