apiVersion: v1
kind: PersistentVolume
metadata:
 name: ucg-volume-code
spec:
 capacity:
   storage: "40Gi"
 accessModes:
   - ReadWriteMany
 nfs:
   server: "fsf-dal1001f-fz.adn.networklayer.com"
   path: "/IBM02SV1339641_1/data01/code"